apiVersion: v1
kind: Service
metadata: 
  name: nginx-Service
spec: 
  type: NodePort
  selector: 
    app: nginx
    colour: blue
  ports: 
    - port : 80
      targetPort: 80
      nodePort: 30001    