apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-blue
spec: 
  replicas: 5
  selector:
    matchLabels:
      app: nginx
      color: blue
  template: 
    metadata: 
      labels: 
        name: nginx
        color: blue
    spec:
      containers: 
        - name: nginx
          image: nginx:1.24